var data = [
  {
    id: 1,
    role: `VENTURE PARTNER`,
    name: `ADAM GOLDBERG`,
    quote:
      "I don’t care about your background or where you started. I care about where you’re going.",
    image: "src/database/images/image-1.png",
    story: `At age 13, Adam enrolled at UC Berkeley, where he studied mathematics and conducted research in number theory and cryptography.<br/>
     He went on to work as a mathematician for the Department of Defense and as a researcher at Lawrence Berkeley National Laboratory, the University of Wisconsin-Madison, and Stanford InfoLab. <br/>
     Adam graduated from Stanford with a BS in computer science, with a concentration in systems. He was also an early product manager at Rubrik, a Lightspeed portfolio company, and moonlighted as a technical consultant for HBO’s Silicon Valley. <br/>
     In 2016, Adam left Rubrik to become a partner at Lightspeed. “My entire life, I’ve optimized for learning,” he says. “Venture is the epitome of learning. You spend all your time with people who are experts in their field. <br/>
     What other job lets you do that?” 
    At Lightspeed he’s focused on investments in blockchain companies and crypto networks, and he cofounded crypto investment firm Standard Crypto in 2019. What does he look for in founders? The first quality is rationality quotient, or RQ—whether or not a person has the humility to recognize what he or she doesn’t know. The second quality is discernment. “If somebody says every meal they have is the best meal of their life, is their judgement really that great? You want the person who can list their top three with a clear mental framework,” he says. But ultimately, he believes the most important quality a founder brings to the table is an eye for the future and a clear idea of what it will take to get there. “I’m used to being the youngest person in the room,” he says. “Because of that, I don’t care about your background or where you started. I care about where you’re going. Potential trumps experience every time.”
    `,
    place: `US`,
  },
  {
    id: 2,
    role: `PARTNER`,
    name: `ADAM SMITH`,
    quote: `"I’m not one to hesitate when it comes to jumping on a plane to meet with an entrepreneur, no matter where in the world.”`,
    image: "src/database/images/image-2.png",
    story: `Adam joined Lightspeed in 2019 as one of the early members of the firm’s growth team, where he focuses on high-growth enterprise and consumer investment opportunities. Having spent time at Uber and also consulting for fast-growing companies, he’s developed an in-depth understanding of what it takes to scale a business across the lifecycle. A dual-citizen who grew up in both Europe and the U.S., Adam attributes much of who he is and how he views the world to his multicultural background. “I always smile when someone asks me where I’m from; there’s no one answer,” says Adam. “Living in London, Munich, and New York during different stages of my life gave me a deep appreciation of different cultural norms and values, openness and adaptability to new experiences and ideas.” In short, he’s not one to hesitate when it comes to jumping on a plane to meet with an entrepreneur, no matter where in the world. Adam started his career as a management consultant at Bain & Company, advising clients on strategic investments and growth opportunities in the healthcare, telecom, and technology industries. His love for problem-solving and hands-on mentality means he’s always happy to roll up his sleeves and get in the trenches. Within a few years, his passion for technology and his desire to be an operator landed him at Uber, where he led the NYC team responsible for optimizing the supply-side of the marketplace. It gave him a firsthand understanding of not only the drivers of success but also the challenges that businesses encounter when trying to maintain a high pace of growth while building the culture and infrastructure required to sustain it over the long-term. Being part of one of the most disruptive companies of the last decade equipped Adam to identify and navigate the hurdles entrepreneurs face: “I walked away with a tremendous amount of respect for founders. Building a successful business invariably means grappling with difficult choices and balancing trade-offs. It requires the utmost dedication, tenacity, and a willingness to make sacrifices.” Adam came to Lightspeed from Bain Capital Ventures, where he looked at early-to-late stage investments in application software across both verticals and horizontals. During his time there, he developed segment expertise in financial technology. Adam graduated magna cum laude from UPenn with a degree in Neurobiology. He has an adventurous spirit and in his free time, you can find him backcountry skiing, kitesurfing, and climbing.`,
    place: `US`,
  },
  {
    id: 3,
    role: `PARTNER`,
    name: `ALEX TAUSSIG`,
    quote: `The single activity I've practiced more than any other is asking the best possible question and listening hard to the answer.`,
    image: "src/database/images/image-3.png",
    story: `Alex has spent over a decade in venture capital, joining Lightspeed as a Partner in early 2016. He is passionate about understanding consumer behavior through data and has spent his career investing in startups addressing consumers’ needs. Alex’s investments have covered consumer categories as diverse as retail, apparel, media, publishing, real estate, and education. Alex is a trained research scientist and breaks down business problems with deductive logic and analytical rigor. He originally studied physics at Harvard College, where he graduated summa cum laude, and then went on to receive a Master’s degree in materials engineering from MIT, where he was part of a research group building the first fully optical computer chip. Alex also received an MBA from Harvard Business School, where he was a Baker Scholar, an honor given to the top 5% of the graduating class. At Lightspeed, Alex is a partner on the consumer investment team, where he has led Lightspeed’s early investments in AWA Studios, Daily Harvest, Faire, Forage, Jumprope, Outschool, Zola, and several unannounced digital media startups. Alex publishes a popular weekly newsletter called DRINKING FROM THE FIREHOSE,which covers recent news across commerce, media, tech, science, and popular culture. He lives in San Francisco with his wife and two children.`,
    place: `Us`,
  },
  {
    id: 4,
    role: `PARTNER`,
    name: `AMY WU`,
    quote: `“As a former operator, what I love most about investing is getting in the trenches with CEOs and their teams.”`,
    image: "src/database/images/image-4.png",
    story: `Amy has enjoyed being on both sides of the table as investor and operator, joining Lightspeed in 2019 as an early member of the growth team to lead the reinvestment platform and invest in growth-stage consumer and enterprise businesses. Prior to Lightspeed, Amy was an executive for several years, most recently at Discovery, Inc, a global media company with 17 TV networks in 220 countries, and at NewsCred, a growth-stage marketing software company based in NYC, after starting her career at Insight Venture Partners. Amy’s breadth of experience – in early-stage and corporate, in consumer and enterprise businesses, and across the US, Europe, and Asia – has deeply shaped her passion for helping businesses scale globally. In the US, Amy helped raise over $60M for NewsCred, was group CFO of 4 US direct-to-consumer businesses at Discovery and was involved with Zumba, DrillingInfo, and other marketplace and SaaS investments while at Insight. In Europe, Amy was group CFO of Discovery Eurosport, the leading sports broadcaster across Europe, and DPlay, an on-demand video streaming platform, and led the acquisition of Playsports UK. Finally, Amy has lived and invested in Asia, where she was born in Beijing, was CFO and SVP of Commercial Operations for Discovery Asia based in Singapore, led the Scripps Networks Asia integration efforts, and was a board observer with JD.com while at Insight. “As a former operator, what I love most about investing is getting in the trenches with CEOs and their teams.” Amy finds balance in her life in the outdoors. Having grown up in Oregon, Amy loves skiing on and off-piste, rock climbing, and has summited over 12 alpine peaks over 10,000 ft high. “Mountaineering is the most humbling experience. It gives me real perspective in life and keeps me calm when helping my team and companies through good and hard times.”`,
    place: `US`,
  },
  {
    id: 5,
    role: `OPERATING PARTNER + CFO`,
    name: `ANDREW MOLEY`,
    quote: `Don’t turn down interesting things because they’re risky — risky things challenge you the most. And challenges lead to better opportunities.`,
    image: "src/database/images/image-5.png",
    story: `As operating partner and CFO of Lightspeed since 2008, Andrew provides financial and operational oversight for the firm, which supports more than 200 portfolio companies. As he puts it, “No crises mean it’s been a good day.” When obstacles do arise, Andrew makes sure people have what they need to get on with the work in front of them. Andrew grew up in Silicon Valley, with a front row seat to the evolution of business and technology happening there. “From early age, the startup world has always intrigued me.” He watched his father work incredibly hard with some of the smartest people in the valley. It taught him that when you join a company with people who are smart, humble and hardworking, remarkable things can happen. Andrew was drawn to Lightspeed because of the passion each team member has for their work. What really excites him is the constant pursuit of new ideas that happens every day. “At Lightspeed, every day holds something new.” He brings extensive executive experience to the firm, having developed and led both public and private companies throughout his career. Prior to joining Lightspeed, Andrew was CFO of three venture-backed startups. He served as CFO of eGreetings Network (EGRT), taking the company public in 1999, and later took over as the CEO of the company until its sale to American Greetings (AM) in 2001. He also served as EVP and CFO of CMC Industries (CMCI), a publicly traded EMS company. He began his career at Mercer Management Consulting. Andrew has a BS in economics from The Wharton School of the University of Pennsylvania. He also holds an MBA from Stanford University Graduate School of Business where he returns annually as a guest lecturer. His advice to making it in the industry? Focus on what you do well. Work with people who challenge you. Follow leads that come to you. And ultimately, he says, “Don’t turn down interesting things because they’re risky — risky things challenge you the most. And challenges lead to better opportunities.”`,
    place: `US`,
  },
  {
    id: 6,
    role: `PARTNER, INVESTOR RELATIONS`,
    name: `ANGELA SIBLEY`,
    quote: `“There is so much to learn from taking the time to step back and ask ‘why?’”`,
    image: "src/database/images/image-6.png",
    story: `As Partner of Investor Relations, Angela is responsible for Lightspeed’s global investor relationships. This role combines Angela’s extensive experience working with a range of global investors and her passion for helping leaders of high growth, industry-leading companies. Prior to joining Lightspeed, Angela was a principal of investor relations and marketing with Capital Group Private Markets, the emerging markets private equity arm of the Capital Group. She also spent time in Greenwich, Connecticut as Vice President of investor relations for Alinda Capital Partners. Angela began her career at Standard Chartered Bank, working in both London and Singapore in multiple roles spanning principal finance investor relations, chief of staff to the group chairman, relationship management, and global equity research. It was the experience of working internationally across three continents that led Angela to develop an interest in venture capital. “Seeing businesses starting in Asia that was replicating, and often improving on, US-based early-stage ventures, made it clear to me that in this global world, timing and execution are just as important as getting a business model right,” she says. “I have always loved meeting entrepreneurs and being around the passion they bring to their work”. Angela holds a BSc in statistics with first class honors from University College London and an MS in management degree from Stanford Graduate School of Business. Outside of work she enjoys traveling and immersing herself in as many new cultures as possible.`,
    place: `US`,
  },
  {
    id: 7,
    role: `PARTNER`,
    name: `ANOUSHKA VASWANI`,
    quote: `"There is no one-size fits all model for success"`,
    image: "src/database/images/image-7.png",
    story: `Growing up moving from the United Arab Emirates to Turkey to Brussels to the United States, Anoushka has always embraced looking at life from multiple perspectives. “That experience gave me a strong appreciation for different people, cultures, and backgrounds,” she says. “And a deep belief that there is no one-size fits all model for success.” Anoushka has experience investing at multiple stages within the venture industry. Before Lightspeed, she was an investor at Matrix, supporting entrepreneurs raising their first rounds of funding, and now Lightspeed, Anoushka focuses on investments in growth-stage companies within the enterprise software and infrastructure ecosystems. “Today, founders have more options but also face more challenges about how to sustainably scale their business,” says Anoushka. “It’s important to partner with a team that can support an entrepreneur at every stage of his or her business.” Before Lightspeed, she also served as the third product manager at MasterClass, while the company scaled from 50 to 80 employees. “A company is a sum of the people within it.  The best leaders are not fungible – their impact is far-reaching and indelible on the culture they create.” Anoushka began her career working with technology companies at Goldman and McKinsey, where she led the firm’s first project with Facebook on the launch of internet.org. She double majored in Economics and Psychology at Columbia, where she graduated summa cum laude and Phi Beta Kappa, and then went to Harvard where she earned her MBA. In her spare time, she enjoys running along the Embarcadero and curates a monthly newsletter called THE MAIL which focuses on themes in growth-stage venture investing, scaling companies, and enterprise software.`,
    place: `US`,
  },
  {
    id: 8,
    role: `PARTNER`,
    name: `ANSAF KAREEM`,
    quote: `With the right entrepreneur and team, big ideas could move quickly and catalyze change in amazing ways.`,
    image: "src/database/images/image-8.png",
    story: `It’s only natural that Ansaf approaches venture capital from the perspective that “technology and entrepreneurship are great sources of positive change.” After all, he grew up at the intersection of technology and humanitarianism: His father was an electrical engineer and technologist, and his mother was a doctor who started a social-service organization to aid refugees in his hometown of Portland, Oregon. <br/>
    But his path to venture capital was a circuitous one. His studies took him from Stanford, where he graduated with honors and served as class president, to Harvard, where he earned an MBA and an MPP. Ansaf was one of the first ten World Economic Forum (WEF) Young Global Shapers, a member of the Aspen Institute’s Impact Careers Initiative, and a Policy Fellow for Senator Cory Booker. Ansaf was always attracted to organizations and initiatives that sought to solve problems of great proportion. <br/> 
    “I’ve always believed that government can be a big lever of change,” he says. “But I also realized that technology was an accelerant that was changing the world at an alarming pace. Coupled with the right entrepreneur and team, big ideas could move quickly and catalyze change in amazing ways.” <br/>
    Ansaf began his career as a management consultant for McKinsey & Company in New York, working with the largest enterprises in the world on their most painful strategic and operational problems. Then he joined the product team at RelateIQ, an early-stage enterprise SaaS company building a next-gen CRM platform applying machine learning and data science to one of the most crucial workflows in the enterprise. RelateIQ was acquired by Salesforce for more than $400 million, and Ansaf’s path ultimately led him to Lightspeed, where he joined as a partner in 2016. <br/>
    “What excited me about Lightspeed in particular was the flat culture and hustle mentality within the firm,” he says. “We are constantly pushing the bar higher for ourselves, looking for ways to keep moving quickly while improving ourselves and our approach to better serve the entrepreneurs we work with—a necessary quality when our business involves partnering with individuals dreaming up the next great technology and looking to create a seismic impact on the world.”`,
    place: `US`,
  },
];
export default data;
