const data = [
  {
    id: 1,
    role: `VENTURE PARTNER`,
    name: `ADAM GOLDBERG`,
    quote:
      "I don’t care about your background or where you started. I care about where you’re going.",
    image: "src/database/images/image-1.png",
    story: `At age 13, Adam enrolled at UC Berkeley, where he studied mathematics and conducted research in number theory and cryptography. He went on to work as a mathematician for the Department of Defense and as a researcher at Lawrence Berkeley National Laboratory, the University of Wisconsin-Madison, and Stanford InfoLab. Adam graduated from Stanford with a BS in computer science, with a concentration in systems. He was also an early product manager at Rubrik, a Lightspeed portfolio company, and moonlighted as a technical consultant for HBO’s Silicon Valley. In 2016, Adam left Rubrik to become a partner at Lightspeed. “My entire life, I’ve optimized for learning,” he says. “Venture is the epitome of learning. You spend all your time with people who are experts in their field. What other job lets you do that?” 
    At Lightspeed he’s focused on investments in blockchain companies and crypto networks, and he cofounded crypto investment firm Standard Crypto in 2019. What does he look for in founders? The first quality is rationality quotient, or RQ—whether or not a person has the humility to recognize what he or she doesn’t know. The second quality is discernment. “If somebody says every meal they have is the best meal of their life, is their judgement really that great? You want the person who can list their top three with a clear mental framework,” he says. But ultimately, he believes the most important quality a founder brings to the table is an eye for the future and a clear idea of what it will take to get there. “I’m used to being the youngest person in the room,” he says. “Because of that, I don’t care about your background or where you started. I care about where you’re going. Potential trumps experience every time.”
    `,
    place: `US`,
  },
  {
    id: 2,
    role: `PARTNER`,
    name: `ADAM SMITH`,
    quote: `"I’m not one to hesitate when it comes to jumping on a plane to meet with an entrepreneur, no matter where in the world.”`,
    image: "src/database/images/image-2.png",
    story: `Adam joined Lightspeed in 2019 as one of the early members of the firm’s growth team, where he focuses on high-growth enterprise and consumer investment opportunities. Having spent time at Uber and also consulting for fast-growing companies, he’s developed an in-depth understanding of what it takes to scale a business across the lifecycle. A dual-citizen who grew up in both Europe and the U.S., Adam attributes much of who he is and how he views the world to his multicultural background. “I always smile when someone asks me where I’m from; there’s no one answer,” says Adam. “Living in London, Munich, and New York during different stages of my life gave me a deep appreciation of different cultural norms and values, openness and adaptability to new experiences and ideas.” In short, he’s not one to hesitate when it comes to jumping on a plane to meet with an entrepreneur, no matter where in the world. Adam started his career as a management consultant at Bain & Company, advising clients on strategic investments and growth opportunities in the healthcare, telecom, and technology industries. His love for problem-solving and hands-on mentality means he’s always happy to roll up his sleeves and get in the trenches. Within a few years, his passion for technology and his desire to be an operator landed him at Uber, where he led the NYC team responsible for optimizing the supply-side of the marketplace. It gave him a firsthand understanding of not only the drivers of success but also the challenges that businesses encounter when trying to maintain a high pace of growth while building the culture and infrastructure required to sustain it over the long-term. Being part of one of the most disruptive companies of the last decade equipped Adam to identify and navigate the hurdles entrepreneurs face: “I walked away with a tremendous amount of respect for founders. Building a successful business invariably means grappling with difficult choices and balancing trade-offs. It requires the utmost dedication, tenacity, and a willingness to make sacrifices.” Adam came to Lightspeed from Bain Capital Ventures, where he looked at early-to-late stage investments in application software across both verticals and horizontals. During his time there, he developed segment expertise in financial technology. Adam graduated magna cum laude from UPenn with a degree in Neurobiology. He has an adventurous spirit and in his free time, you can find him backcountry skiing, kitesurfing, and climbing.`,
    place: `US`,
  },
];
